package com.antigravity.mobile.ui.components

import android.annotation.SuppressLint
import android.os.Handler
import android.os.Looper
import android.util.LruCache
import android.webkit.JavascriptInterface
import android.webkit.WebSettings
import android.webkit.WebView
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.animateContentSize
import androidx.compose.animation.core.spring
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import com.antigravity.mobile.data.model.FileContentResponse
import com.antigravity.mobile.data.service.ApiClient
import com.antigravity.mobile.data.service.PreferencesManager
import com.antigravity.mobile.ui.theme.AntigravityTheme
import com.antigravity.mobile.ui.theme.AppColors
import com.antigravity.mobile.ui.util.rememberHaptic
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request

/**
 * In-memory cache for loaded Agent Embed HTML content.
 */
object AgentEmbedCache {
    private val cache = LruCache<String, String>(100)

    fun get(src: String): String? = cache.get(src)
    fun put(src: String, content: String) {
        cache.put(src, content)
    }
    fun remove(src: String) {
        cache.remove(src)
    }
}

/**
 * Shared client for the no-[ApiClient] fallback path, so repeated loads reuse one connection pool
 * and dispatcher instead of building a new [OkHttpClient] per card.
 */
private val fallbackHttpClient: OkHttpClient by lazy { OkHttpClient() }

/**
 * 1:1 Jetpack Compose implementation of iOS AgentEmbedView.swift.
 * Displays interactive, embedded HTML cards generated by agents (Generative UI).
 */
@Composable
fun AgentEmbedView(
    src: String,
    colors: AppColors = AntigravityTheme.colors,
    urlResolver: ((String) -> String)? = null,
    modifier: Modifier = Modifier
) {
    var htmlContent by remember { mutableStateOf<String?>(null) }
    var isLoading by remember { mutableStateOf(false) }
    var errorMessage by remember { mutableStateOf<String?>(null) }
    var detectedTitle by remember { mutableStateOf<String?>(null) }
    var embedHeightDp by remember { mutableStateOf(340.dp) }
    var isFullscreen by remember { mutableStateOf(false) }
    var reloadTrigger by remember { mutableStateOf(0) }

    val haptic = rememberHaptic()
    val isDark = isSystemInDarkTheme()
    val context = LocalContext.current
    val fallbackBaseUrl = remember(context) { PreferencesManager(context).gatewayBaseUrl }

    val defaultTitle = remember(src) {
        val clean = src.trim('`', '"', '\'', '(', ')', '[', ']', '<', '>')
        val fileName = clean.substringAfterLast('/')
        val nameWithoutExt = fileName.substringBeforeLast('.')
        if (nameWithoutExt.isNotBlank() && nameWithoutExt != "interactive_preview" && nameWithoutExt != "widget") {
            nameWithoutExt
        } else {
            "交互预览"
        }
    }

    LaunchedEffect(src, reloadTrigger) {
        val cached = AgentEmbedCache.get(src)
        if (cached != null) {
            htmlContent = cached
            errorMessage = null
            return@LaunchedEffect
        }

        isLoading = true
        errorMessage = null

        // Try primary ApiClient instance first
        val clientInstance = ApiClient.defaultInstance
        if (clientInstance != null) {
            val result: Result<FileContentResponse> = clientInstance.fetchFileContent(src)
            isLoading = false
            result.onSuccess { resp ->
                AgentEmbedCache.put(src, resp.content)
                htmlContent = resp.content
                errorMessage = null
            }.onFailure { err ->
                errorMessage = err.localizedMessage ?: "加载失败"
            }
        } else if (urlResolver != null) {
            // Fallback via resolved media raw/content URL
            val resolvedUrl = urlResolver(src)
            val contentUrl = if (resolvedUrl.contains("/api/v1/files/raw")) {
                resolvedUrl.replace("/api/v1/files/raw", "/api/v1/files/content")
            } else {
                resolvedUrl
            }
            try {
                val req = Request.Builder().url(contentUrl).build()
                val respStr = withContext(Dispatchers.IO) {
                    fallbackHttpClient.newCall(req).execute().use { resp ->
                        if (!resp.isSuccessful) throw RuntimeException("HTTP ${resp.code}")
                        resp.body?.string() ?: ""
                    }
                }
                isLoading = false
                val content = if (respStr.trim().startsWith("{") && respStr.contains("\"content\":")) {
                    val jsonObj = org.json.JSONObject(respStr)
                    jsonObj.optString("content", respStr)
                } else {
                    respStr
                }
                AgentEmbedCache.put(src, content)
                htmlContent = content
                errorMessage = null
            } catch (e: Exception) {
                isLoading = false
                errorMessage = e.localizedMessage ?: "网络异常"
            }
        } else {
            isLoading = false
            errorMessage = "未配置网关连接"
        }
    }

    Column(
        modifier = modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(12.dp))
            .background(colors.surfaceVariant.copy(alpha = 0.45f))
            .border(0.8.dp, colors.border.copy(alpha = 0.4f), RoundedCornerShape(12.dp))
            .animateContentSize(spring(dampingRatio = 0.82f))
    ) {
        // Header Bar
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .background(colors.surfaceVariant.copy(alpha = 0.75f))
                .padding(horizontal = 12.dp, vertical = 7.dp),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.SpaceBetween
        ) {
            Row(
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(6.dp)
            ) {
                Icon(
                    imageVector = Icons.Default.Tune,
                    contentDescription = null,
                    tint = colors.accentIndigo,
                    modifier = Modifier.size(13.dp)
                )

                Text(
                    text = detectedTitle ?: defaultTitle,
                    color = colors.textPrimary,
                    fontSize = 12.sp,
                    fontWeight = FontWeight.SemiBold,
                    maxLines = 1
                )

                Box(
                    modifier = Modifier
                        .clip(CircleShape)
                        .background(colors.accentIndigo.copy(alpha = 0.12f))
                        .padding(horizontal = 5.dp, vertical = 1.5.dp)
                ) {
                    Text(
                        text = "INTERACTIVE",
                        color = colors.accentIndigo,
                        fontSize = 9.5.sp,
                        fontWeight = FontWeight.Bold,
                        fontFamily = FontFamily.Monospace
                    )
                }
            }

            Row(
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(4.dp)
            ) {
                // Refresh Button
                IconButton(
                    onClick = {
                        haptic.light()
                        AgentEmbedCache.remove(src)
                        reloadTrigger++
                    },
                    modifier = Modifier.size(24.dp)
                ) {
                    Icon(
                        imageVector = Icons.Default.Refresh,
                        contentDescription = "刷新",
                        tint = colors.textSecondary,
                        modifier = Modifier.size(14.dp)
                    )
                }

                // Fullscreen Button
                if (htmlContent != null && errorMessage == null) {
                    IconButton(
                        onClick = {
                            haptic.light()
                            isFullscreen = true
                        },
                        modifier = Modifier.size(24.dp)
                    ) {
                        Icon(
                            imageVector = Icons.Default.Fullscreen,
                            contentDescription = "全屏查看",
                            tint = colors.textSecondary,
                            modifier = Modifier.size(16.dp)
                        )
                    }
                }
            }
        }

        HorizontalDivider(color = colors.border.copy(alpha = 0.35f), thickness = 0.6.dp)

        // Main Content Area
        Box(
            modifier = Modifier.fillMaxWidth(),
            contentAlignment = Alignment.BottomEnd
        ) {
            when {
                errorMessage != null -> {
                    Column(
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(140.dp)
                            .padding(16.dp),
                        verticalArrangement = Arrangement.Center,
                        horizontalAlignment = Alignment.CenterHorizontally
                    ) {
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(6.dp)
                        ) {
                            Icon(
                                imageVector = Icons.Default.Warning,
                                contentDescription = null,
                                tint = Color(0xFFFF9800),
                                modifier = Modifier.size(15.dp)
                            )
                            Text(
                                text = "交互卡片加载失败",
                                color = colors.textPrimary,
                                fontSize = 12.5.sp,
                                fontWeight = FontWeight.SemiBold
                            )
                        }

                        Spacer(modifier = Modifier.height(4.dp))

                        Text(
                            text = errorMessage ?: "未知错误",
                            color = colors.textSecondary,
                            fontSize = 11.sp,
                            maxLines = 2
                        )

                        Spacer(modifier = Modifier.height(8.dp))

                        Button(
                            onClick = {
                                AgentEmbedCache.remove(src)
                                reloadTrigger++
                            },
                            contentPadding = PaddingValues(horizontal = 14.dp, vertical = 4.dp),
                            shape = CircleShape,
                            colors = ButtonDefaults.buttonColors(
                                containerColor = colors.accentIndigo.copy(alpha = 0.15f),
                                contentColor = colors.accentIndigo
                            ),
                            modifier = Modifier.height(30.dp)
                        ) {
                            Text(text = "重试", fontSize = 11.sp, fontWeight = FontWeight.Medium)
                        }
                    }
                }

                htmlContent != null -> {
                    AgentEmbedWebViewContainer(
                        htmlContent = htmlContent!!,
                        isDark = isDark,
                        baseUrl = ApiClient.defaultInstance?.currentBaseUrl ?: fallbackBaseUrl,
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(embedHeightDp),
                        onHeightMeasured = { hCssPx ->
                            val dpVal = hCssPx.dp
                            embedHeightDp = dpVal.coerceIn(160.dp, 520.dp)
                        },
                        onTitleDetected = { t ->
                            if (detectedTitle == null && t.isNotBlank()) {
                                detectedTitle = t
                            }
                        }
                    )

                    // Subtle hint pill for full-screen expanded action if large
                    if (embedHeightDp >= 480.dp) {
                        Row(
                            modifier = Modifier
                                .padding(8.dp)
                                .clip(CircleShape)
                                .background(colors.surface.copy(alpha = 0.88f))
                                .border(0.5.dp, colors.border.copy(alpha = 0.5f), CircleShape)
                                .clickable {
                                    haptic.light()
                                    isFullscreen = true
                                }
                                .padding(horizontal = 8.dp, vertical = 3.5.dp),
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(4.dp)
                        ) {
                            Icon(
                                imageVector = Icons.Default.Fullscreen,
                                contentDescription = null,
                                tint = colors.textMuted,
                                modifier = Modifier.size(11.dp)
                            )
                            Text(
                                text = "全屏操作",
                                color = colors.textSecondary,
                                fontSize = 10.sp,
                                fontWeight = FontWeight.Medium
                            )
                        }
                    }
                }

                else -> {
                    Column(
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(160.dp),
                        verticalArrangement = Arrangement.Center,
                        horizontalAlignment = Alignment.CenterHorizontally
                    ) {
                        CircularProgressIndicator(
                            color = colors.accentIndigo,
                            strokeWidth = 2.dp,
                            modifier = Modifier.size(24.dp)
                        )
                        Spacer(modifier = Modifier.height(8.dp))
                        Text(
                            text = "正在加载交互组件...",
                            color = colors.textSecondary,
                            fontSize = 11.sp
                        )
                    }
                }
            }
        }
    }

    // Fullscreen Dialog Modal
    if (isFullscreen && htmlContent != null) {
        Dialog(
            onDismissRequest = { isFullscreen = false },
            properties = DialogProperties(usePlatformDefaultWidth = false)
        ) {
            Surface(
                modifier = Modifier.fillMaxSize(),
                color = colors.background
            ) {
                Column(modifier = Modifier.fillMaxSize()) {
                    // Top Bar
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .statusBarsPadding()
                            .padding(horizontal = 8.dp, vertical = 6.dp),
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.SpaceBetween
                    ) {
                        IconButton(onClick = { isFullscreen = false }) {
                            Icon(
                                imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                                contentDescription = "Back",
                                tint = colors.textPrimary
                            )
                        }

                        Text(
                            text = detectedTitle ?: defaultTitle,
                            color = colors.textPrimary,
                            fontSize = 15.sp,
                            fontWeight = FontWeight.SemiBold,
                            maxLines = 1
                        )

                        IconButton(onClick = {
                            haptic.light()
                            AgentEmbedCache.remove(src)
                            reloadTrigger++
                        }) {
                            Icon(
                                imageVector = Icons.Default.Refresh,
                                contentDescription = "刷新",
                                tint = colors.accentIndigo
                            )
                        }
                    }

                    HorizontalDivider(color = colors.border.copy(alpha = 0.4f))

                    // Fullscreen WebView
                    AgentEmbedWebViewContainer(
                        htmlContent = htmlContent!!,
                        isDark = isDark,
                        baseUrl = ApiClient.defaultInstance?.currentBaseUrl ?: fallbackBaseUrl,
                        modifier = Modifier
                            .fillMaxWidth()
                            .weight(1f),
                        onHeightMeasured = null,
                        onTitleDetected = null
                    )
                }
            }
        }
    }
}

private data class LoadedHtmlState(val url: String, val html: String)

/**
 * Native Android WebView wrapper rendering Agent Embed HTML.
 */
@SuppressLint("SetJavaScriptEnabled")
@Composable
private fun AgentEmbedWebViewContainer(
    htmlContent: String,
    isDark: Boolean,
    baseUrl: String?,
    modifier: Modifier = Modifier,
    onHeightMeasured: ((Int) -> Unit)? = null,
    onTitleDetected: ((String) -> Unit)? = null
) {
    val enhancedHtml = remember(htmlContent, isDark) {
        AgentEmbedHtmlBuilder.build(htmlContent, isDark)
    }
    val targetBaseUrl = baseUrl ?: "file:///android_asset/"

    AndroidView(
        modifier = modifier,
        factory = { ctx ->
            WebView(ctx).apply {
                setBackgroundColor(android.graphics.Color.TRANSPARENT)
                isVerticalScrollBarEnabled = true
                isHorizontalScrollBarEnabled = false

                settings.apply {
                    javaScriptEnabled = true
                    domStorageEnabled = true
                    allowFileAccess = true
                    loadWithOverviewMode = true
                    useWideViewPort = true
                    setSupportZoom(false)
                    builtInZoomControls = false
                    displayZoomControls = false
                    mixedContentMode = WebSettings.MIXED_CONTENT_ALWAYS_ALLOW
                    cacheMode = WebSettings.LOAD_DEFAULT
                }

                addJavascriptInterface(
                    object {
                        @JavascriptInterface
                        fun postSize(height: Int) {
                            Handler(Looper.getMainLooper()).post {
                                onHeightMeasured?.invoke(height)
                            }
                        }

                        @JavascriptInterface
                        fun postTitle(title: String) {
                            Handler(Looper.getMainLooper()).post {
                                onTitleDetected?.invoke(title)
                            }
                        }
                    },
                    "AndroidAgentEmbedBridge"
                )

                tag = LoadedHtmlState(targetBaseUrl, enhancedHtml)
                loadDataWithBaseURL(targetBaseUrl, enhancedHtml, "text/html", "UTF-8", null)
            }
        },
        update = { webView ->
            val lastState = webView.tag as? LoadedHtmlState
            if (lastState?.url != targetBaseUrl || lastState?.html != enhancedHtml) {
                webView.tag = LoadedHtmlState(targetBaseUrl, enhancedHtml)
                webView.loadDataWithBaseURL(targetBaseUrl, enhancedHtml, "text/html", "UTF-8", null)
            }
        }
    )
}

/**
 * Injects Antigravity theme variables and mobile viewport into HTML content.
 */
private object AgentEmbedHtmlBuilder {
    fun build(html: String, isDark: Boolean): String {
        val darkClass = if (isDark) "dark" else "light"
        val themeCss = """
            <style id="antigravity-embed-injected-theme">
              :root {
                --background: ${if (isDark) "#18181b" else "#ffffff"};
                --foreground: ${if (isDark) "#f4f4f5" else "#18181b"};
                --muted-foreground: ${if (isDark) "#a1a1aa" else "#71717a"};
                --card: ${if (isDark) "#27272a" else "#f4f4f5"};
                --sidebar: ${if (isDark) "#18181b" else "#fafafa"};
                --border: ${if (isDark) "rgba(255, 255, 255, 0.12)" else "rgba(0, 0, 0, 0.10)"};
                --primary: ${if (isDark) "#6366f1" else "#4f46e5"};
                --primary-foreground: #ffffff;
                --secondary: ${if (isDark) "#27272a" else "#e4e4e7"};
                --secondary-foreground: ${if (isDark) "#f4f4f5" else "#18181b"};
                --accent: ${if (isDark) "rgba(255, 255, 255, 0.08)" else "rgba(0, 0, 0, 0.05)"};
                color-scheme: ${if (isDark) "dark" else "light"};
              }
              * {
                box-sizing: border-box;
              }
              html, body {
                margin: 0;
                padding: 8px;
                background: transparent !important;
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
                -webkit-text-size-adjust: 100%;
                -webkit-tap-highlight-color: transparent;
                touch-action: pan-x pan-y;
                overscroll-behavior: none;
              }
              img, svg, video {
                max-width: 100% !important;
              }
            </style>
        """.trimIndent()

        val viewportMeta = """<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, viewport-fit=cover">"""

        val reporterScript = """
            <script id="antigravity-embed-injected-reporter">
              (function() {
                // Prevent gesture zoom
                document.addEventListener('gesturestart', function(e) { e.preventDefault(); }, { passive: false });
                document.addEventListener('gesturechange', function(e) { e.preventDefault(); }, { passive: false });
                document.addEventListener('gestureend', function(e) { e.preventDefault(); });

                function reportSize() {
                  try {
                    var body = document.body;
                    var html = document.documentElement;
                    if (!body) return;
                    var card = body.firstElementChild || body;
                    var rect = card.getBoundingClientRect();
                    var h = Math.ceil(Math.max(rect.height || 0, card.scrollHeight || 0, body.scrollHeight || 0, body.offsetHeight || 0)) + 16;
                    if (!h || h < 80) {
                      h = Math.max(body.scrollHeight, body.offsetHeight, html.clientHeight, html.scrollHeight, html.offsetHeight);
                    }
                    if (h > 0 && window.AndroidAgentEmbedBridge && window.AndroidAgentEmbedBridge.postSize) {
                      window.AndroidAgentEmbedBridge.postSize(Math.round(h));
                    }
                  } catch(e) {}
                }

                function reportTitle() {
                  try {
                    var el = document.querySelector('h1, h2, h3, h4, title');
                    if (el && el.innerText) {
                      var t = el.innerText.trim();
                      if (t.length > 0 && t.length < 50 && window.AndroidAgentEmbedBridge && window.AndroidAgentEmbedBridge.postTitle) {
                        window.AndroidAgentEmbedBridge.postTitle(t);
                      }
                    }
                  } catch(e) {}
                }

                if (document.readyState === 'complete' || document.readyState === 'interactive') {
                  reportSize();
                  reportTitle();
                } else {
                  window.addEventListener('DOMContentLoaded', function() { reportSize(); reportTitle(); });
                  window.addEventListener('load', function() { reportSize(); reportTitle(); });
                }

                if (window.ResizeObserver && document.body) {
                  var ro = new ResizeObserver(function() { reportSize(); });
                  ro.observe(document.body);
                }

                try {
                  Array.from(document.images || []).forEach(function(img) {
                    if (!img.complete) {
                      img.addEventListener('load', reportSize);
                      img.addEventListener('error', reportSize);
                    }
                  });
                } catch(e) {}

                setTimeout(reportSize, 120);
                setTimeout(reportSize, 400);
                setTimeout(reportSize, 1200);
              })();
            </script>
        """.trimIndent()

        // Strip any existing viewport meta tags to prevent conflicting zoom/scale settings
        val vpRegex = Regex("""<meta\s+[^>]*?name=["']viewport["'][^>]*>""", RegexOption.IGNORE_CASE)
        var modified = vpRegex.replace(html, "")
        if (modified.contains("<html")) {
            modified = if (modified.contains("class=\"")) {
                modified.replace("class=\"", "class=\"$darkClass ")
            } else {
                modified.replace("<html", "<html class=\"$darkClass\"")
            }
        }

        val injections = "\n$viewportMeta\n$themeCss\n$reporterScript\n"
        return when {
            modified.contains("<head>", ignoreCase = true) -> {
                val idx = modified.indexOf("<head>", ignoreCase = true) + 6
                modified.substring(0, idx) + injections + modified.substring(idx)
            }
            modified.contains("<html>", ignoreCase = true) -> {
                val idx = modified.indexOf("<html>", ignoreCase = true) + 6
                modified.substring(0, idx) + "<head>$injections</head>" + modified.substring(idx)
            }
            else -> {
                "<!DOCTYPE html><html class=\"$darkClass\"><head>$injections</head><body>$modified</body></html>"
            }
        }
    }
}
